#!/bin/bash
### BEGIN INIT INFO
# Provides:       avf-set-root-password
# Required-Start: avf-configure-networking
# Required-Stop:  
# Should-Start:   
# Should-Stop:    
# Default-Start:  1 2 3
# Default-Stop:   
# Description:    sets the root password from the MDS data on first boot
### END INIT INFO
# chkconfig: 123 99 99

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

MDS="http://[fc0f::fee]/2013-09-14/"

mds() {
    local path="$1"
    /usr/bin/wget -qO - "$MDS/$path"
}

log() {
    local p="$(basename $0)"
    echo "$p - $@" >> /var/log/syslog

    /usr/bin/logger -t $p "$@"
}

rootpass="$(mds root_password)"

# We only want to do this on our first boot!

if [ -f "/etc/set-root-password" ]; then
    if [ -z "${rootpass}" ]; then
        log "Failed to get root password from MDS"
        exit 0
    fi

    log "Setting the root password to the value in MDS / on bulkhead"
    /bin/echo "root:${rootpass}" | /usr/sbin/chpasswd -e

    /bin/rm -f /etc/set-root-password
fi
