#!/bin/bash
### BEGIN INIT INFO
# Provides:       avf-configure-puppet
# Required-Start: avf-configure-networking
# Required-Stop:  
# Should-Start:   
# Should-Stop:    
# Default-Start:  1 2 3
# Default-Stop:   
# Description:    Retrieve SSH user keys and seed the avf user's authorized_keys
### END INIT INFO
# chkconfig: 123 99 99

MDS="http://[fc0f::fee]/2013-09-14/"

mds() {
    local path="$1"
    wget -qO - "$MDS/$path"
}

log() {
    local p="$(basename $0)"
    echo "$p - $@" >> /var/log/syslog
    
    logger -t $p "$@"
}

puppetserver="$(mds puppet/server)"

if [ -z "$puppetserver" ]; then
    log "Failed to get Puppet server details from MDS"
    exit 0
fi

log "Setting Puppet server to $puppetserver"
sed -i "s/PUPPETSERVER/$puppetserver/" /etc/puppet/puppet.conf

mkdir -p /var/lib/puppet/ssl/certs

if [ -n "$(mds puppet/ca)" ]; then
    log "Setting puppet CA cert"
    mds puppet/ca >/var/lib/puppet/ssl/certs/ca.pem
fi

if [ -n "$(mds puppet/cert)" ]; then
    mkdir -p /var/lib/puppet/ssl/certs
    log "Setting puppet client cert"
    mds puppet/cert >/var/lib/puppet/ssl/certs/$(hostname -f).pem
fi

if [ -n "$(mds puppet/key)" ]; then
    mkdir -p /var/lib/puppet/ssl/certs
    log "Setting puppet client private key"
    mds puppet/key >/var/lib/puppet/ssl/private_keys/$(hostname -f).pem
fi

# Now... run ourselves some Puppet!
i=0

puppet agent --enable

while [ "$i" -lt "6" ]; do
    puppet agent --test --detailed-exitcodes
    rm -f /var/lib/puppet/ssl/certs/imagebuildtest.anchor.net.au.pem
    if [ "$?" != "0" ]; then
        echo "Not converged yet; let's try again"
    else
        break
    fi
    i=$(($i+1))
done

if [ "$i" = "6" ]; then
    echo "PUPPET FAILED TO CONVERGE.  THIS SUCKS."
else
    echo "Going down for a reboot now..."
    log "Rebooting the machine after puppet run."
    sleep 5
    reboot
fi

if [ -f "/var/log/editr.log"]; then 
	rm -rf /var/log/editr.log
fi
